apiVersion: v1
kind: Service
metadata:
  name: dnsarc-dns-service
  labels:
    app: dnsarc-dns
spec:
  selector:
    app: dnsarc-dns
  ports:
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
  type: ClusterIP